# Generated by Django 4.0.6 on 2022-08-08 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_taskcaserelevance_case'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcaserelevance',
            old_name='case',
            new_name='cases',
        ),
    ]
