# Generated by Django 4.0.2 on 2022-04-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_rename_result_testcase_response_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='is_Delete',
            new_name='is_delete',
        ),
    ]
